#!/usr/bin/env bash
# script to install nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# test config
sudo nginx -t

# restart nginx
sudo service restart
