#!/usr/bin/env bash
# same as the task before -f added to ln to force remove the file if it exists.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
