#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH agent
eval $("ssh-agent")

# Path to identityFile
ssh-add ~/alx-system_engineering-devops/0x0B-ssh/school.pub

# Username and IP Address 
ssh ubuntu@54.236.53.159
